import SwiftUI

struct VerdadORetoView: View {
    @State private var challengeText: String = ""

    var body: some View {
        VStack {
            Text(challengeText)
                .font(.system(size: 18))
                .foregroundColor(.white)
                .padding()

            Button(action: {
                showRandomChallenge()
            }) {
                Text("Otro reto".uppercased())
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color.gray)
                    .cornerRadius(25)
            }
            .padding()
        }
        .onAppear {
            showRandomChallenge()
        }
    }
    
    private func showRandomChallenge() {
        // Mostrar reto o verdad
        let isVerdad = Bool.random()
        challengeText = isVerdad ? "Verdad: \(verdades.randomElement() ?? "")" : "Reto: \(retos.randomElement() ?? "")"
    }
    
    let verdades: [String] = [
        "¿Alguna vez te has enamorado de alguien prohibido?",
        "¿Qué es lo más vergonzoso que has hecho en público?",
        "¿Has mentido para conseguir algo?",
        "¿Cuál es tu mayor miedo?",
        "¿Alguna vez has sido infiel?",
        "¿Qué es lo más loco que has hecho por amor?",
        "¿Has fingido estar enfermo para no ir a trabajar o estudiar?",
        "¿Qué es lo más raro que haces cuando estás solo?",
        "¿Te gusta alguien en esta habitación?",
        "¿Alguna vez has enviado un mensaje a la persona equivocada?",
        "¿Qué es lo más extraño que has comido?",
        "¿Alguna vez has robado algo?",
        "¿Cuál es tu secreto más vergonzoso?",
        "¿Qué es lo más infantil que todavía haces?",
        "¿Qué es lo más ilegal que has hecho?",
        "¿Alguna vez has tenido un amor secreto por alguien en este grupo? ¿Quién?",
        "¿Qué es lo más vergonzoso que has hecho por intentar impresionar a alguien?",
        "¿Alguna vez te has enamorado de alguien que no correspondía a tus sentimientos?",
        "¿Cuál es el peor rumor que has oído sobre ti mismo/a?",
        "¿Alguna vez has hecho trampa en un juego o examen? ¿Cómo?",
        "¿Te has enamorado alguna vez de tu mejor amigo/a? ¿Lo dijiste?",
        "¿Alguna vez te has quedado con alguien solo por interés?",
        "¿Alguna vez has utilizado las redes sociales para espiar a alguien? ¿A quién?",
        "¿Cuál es tu mayor inseguridad física?",
        "¿Alguna vez has besado a alguien sin que te gustara realmente? ¿Por qué?",
        "¿Has dicho alguna vez 'te quiero' sin sentirlo de verdad?",
        "¿Has tenido alguna cita desastrosa? ¿Qué pasó?",
        "¿Cuál ha sido el momento más incómodo de tu vida en público?",
        "¿Alguna vez has mentido sobre tu edad o tu trabajo?",
        "¿Cuál es el mayor error que has cometido en una relación?",
        "¿Alguna vez has fingido estar enfermo/a para evitar algo?",
        "¿Te has enamorado alguna vez de una persona prohibida o fuera de tus principios?",
        "¿Has llorado viendo una película? ¿Cuál?",
        "¿Alguna vez has hablado dormido?",
        "¿Qué es lo más embarazoso que has dicho a alguien?",
        "¿Qué harías si fueras del género opuesto por un día?",
        "¿Cuál es tu apodo más extraño?",
        "¿Alguna vez te han rechazado?",
        "¿Qué es lo peor que has hecho estando borracho?",
        "¿Alguna vez te has dormido en clase o en el trabajo?",
        "¿Qué mentira dices más seguido?",
        "¿Has usado la cuenta de alguien sin permiso?",
        "¿Alguna vez has sido atrapado mintiendo?",
        "¿Qué es lo más loco que harías por dinero?",
        "¿Alguna vez has fingido reírte de un chiste que no entendiste?",
        "¿Qué es lo más embarazoso que alguien te ha pillado haciendo?",
        "¿Qué parte de tu cuerpo te gusta más?",
        "¿Has stalkeado a alguien en redes sociales?",
        "¿Qué piensas realmente de la persona a tu izquierda?",
        "¿Cuál es tu peor cita?",
        "¿Cuál es tu mayor arrepentimiento?",
        "¿Qué es lo más raro que has buscado en internet?",
        "¿Has hecho trampa en un juego?",
        "¿Qué harías si te tocase la lotería?",
        "¿Alguna vez has fingido estar en una relación?",
        "¿Qué es lo más raro que llevas en tu bolso o mochila?",
        "¿Has tenido un sueño embarazoso? ¿Sobre qué?",
        "¿Qué es lo peor que has publicado en redes sociales?",
        "¿Cuál es tu peor hábito?",
        "¿Alguna vez has dejado a alguien en visto intencionalmente?",
        "¿Qué canción te avergüenza admitir que te gusta?",
        "¿Alguna vez has mentido en este juego?",
        "¿Qué rumor más loco has escuchado sobre ti?",
        "¿Alguna vez te has escapado de casa?",
        "¿Qué es lo más absurdo que has llorado?",
        "¿Qué animal te gustaría ser y por qué?",
        "¿Qué superpoder tendrías si pudieras elegir uno?",
        "¿Qué es lo más embarazoso que has hecho en casa de otra persona?",
        "¿Alguna vez has mentido para no salir con alguien?",
        "¿Qué cosa tonta pensabas que era verdad cuando eras pequeño/a?",
        "¿Qué es lo más vergonzoso que alguien te ha contado sobre ti mismo/a?",
        "¿Alguna vez te has puesto algo que no era tuyo sin pedir permiso?",
        "¿Qué es lo más raro que has dicho en un momento incómodo?",
        "¿Alguna vez has tenido un apodo que odiabas? ¿Cuál era?",
        "¿Qué es lo más embarazoso que has buscado en tu historial de internet?",
        "¿Cuál es el objeto más inútil que has comprado pero aún conservas?",
        "¿Alguna vez has hablado mal de alguien sin darte cuenta de que estaba escuchando?",
        "¿Qué es lo más vergonzoso que has publicado por accidente?",
        "¿Has fingido saber algo que en realidad no entendías? ¿Qué era?",
        "¿Alguna vez te has quedado atascado/a en un lugar extraño? ¿Cómo fue?",
        "¿Qué es lo más raro que has encontrado en casa de alguien?",
        "¿Alguna vez te has reído en un momento completamente inapropiado? ¿Qué pasó?",
        "¿Qué es lo más raro que has comido por curiosidad?",
        "¿Alguna vez has tenido un accidente embarazoso en público?",
        "¿Qué cosa absurda o infantil sigues haciendo porque te gusta?",
        "¿Cuál es el regalo más raro o inútil que has recibido?",
        "¿Qué es lo más raro que te han pillado haciendo en casa?",
        "¿Alguna vez has inventado una excusa increíblemente mala para evitar algo?",
        "¿Qué es lo más embarazoso que has dicho en voz alta sin darte cuenta?",
        "¿Alguna vez has olvidado algo importante de alguien cercano? ¿Qué era?",
        "¿Qué es lo más extraño que has hecho mientras estabas aburrido/a?",
        "¿Alguna vez te has sentido celoso/a sin motivo?",
        "¿Cuál es la cosa más vergonzosa que alguien ha encontrado en tu habitación?",
        "¿Qué apodo secreto usaban contigo y nunca te gustó?",
        "¿Alguna vez has hecho algo vergonzoso para llamar la atención de alguien?",
        "¿Qué hábito extraño tienes pero nadie lo sabe?",
        "¿Cuál es el mayor error que has cometido frente a una persona importante?",
        "¿Alguna vez has escuchado una conversación que no debías? ¿Qué era?",
        "¿Cuál es el peor regalo que has dado a alguien?",
        "¿Qué es lo más raro que has hecho para evitar una responsabilidad?",
        "¿Alguna vez has arruinado una sorpresa sin querer?",
        "¿Qué es lo más extraño que has hecho mientras estabas medio dormido/a?",
        "¿Cuál es tu mayor arrepentimiento de compras impulsivas?",
        "¿Qué es lo más absurdo por lo que has discutido con alguien?",
        "¿Alguna vez has intentado copiar algo y te han descubierto?",
        "¿Cuál es la peor mentira que has dicho en una primera impresión?",
        "¿Qué es lo más raro que has guardado y no sabes por qué?",
        "¿Alguna vez te han pillado hablando solo/a? ¿Qué dijiste?",
        "¿Cuál es tu mayor secreto de la infancia?",
        "¿Alguna vez has hecho algo vergonzoso pensando que nadie te veía?",
        "¿Qué cosa tonta hiciste cuando intentabas impresionar a alguien?",
        "¿Qué es lo más raro que has hecho por una apuesta?",
        "¿Alguna vez has olvidado el nombre de alguien justo después de que se presentó?",
        "¿Cuál es la cosa más embarazosa que tus padres han descubierto sobre ti?"
    ]
    
    let retos: [String] = [
        "Baila sin música durante 1 minuto.",
        "Canta el coro de tu canción favorita.",
        "Imita a alguien en esta habitación hasta que lo adivinen.",
        "Habla con acento extranjero durante 5 minutos.",
        "Envía un mensaje embarazoso a un contacto al azar.",
        "Baila como un robot durante 2 minutos.",
        "Llama a tu ex y dile que aún lo/la extrañas (aunque no sea cierto).",
        "Manda un mensaje a la persona que menos esperas y dile 'Tengo que decirte algo importante...' y luego detén la conversación.",
        "Publica una foto en redes sociales que te dé vergüenza.",
        "Haz una imitación de tu cantante favorito frente a todos durante 1 minuto.",
        "Haz una llamada telefónica a una persona al azar y canta una canción completa.",
        "Envía un mensaje de voz a un grupo diciendo algo vergonzoso que nunca le dirías a nadie en persona.",
        "Haz una video llamada a alguien que no esperas y canta una canción en medio de la llamada.",
        "Actúa como un animal de tu elección durante 2 minutos frente a todos.",
        "Haz una publicación en tus redes sociales diciendo algo completamente falso sobre ti.",
        "Haz 10 sentadillas en 30 segundos sin parar.",
        "Publica un mensaje agradeciendo a tu madre por lo que sea en redes sociales.",
        "Haz 10 flexiones ahora.",
        "Come algo con los ojos cerrados.",
        "Dibuja un retrato de alguien en la habitación.",
        "Haz un sonido de animal y no pares hasta que alguien adivine cuál es.",
        "Habla solo con rimas durante 5 minutos.",
        "Haz una declaración de amor dramática a un objeto cercano.",
        "Canta una canción sin abrir la boca.",
        "Haz una imitación de un famoso.",
        "Haz un TikTok improvisado con alguien.",
        "Escribe un mensaje romántico al último contacto en tu móvil.",
        "Corre alrededor de la habitación como un avión.",
        "Di el abecedario al revés lo más rápido que puedas.",
        "Habla en voz de bebé durante 2 minutos.",
        "Ponte calcetines en las manos y actúa como un muñeco de calcetines.",
        "Di 3 cosas embarazosas sobre ti.",
        "Come algo con salsa picante.",
        "Haz una foto ridícula y súbela a tus redes sociales.",
        "Dibuja algo en tu cara con un bolígrafo.",
        "Habla como si estuvieras en una película épica durante 5 minutos.",
        "Cuenta un chiste malo y haz que todos se rían.",
        "Baila con alguien al ritmo de una canción que elijan los demás.",
        "Pon una canción y canta lo más fuerte que puedas.",
        "Hazte pasar por otra persona de la habitación durante 3 minutos.",
        "Habla como un robot hasta tu próximo turno.",
        "Haz una broma telefónica a alguien al azar.",
        "Ve al baño y cámbiate algo de ropa al revés.",
        "Ponte 3 cosas absurdas en la cabeza como sombrero.",
        "Actúa como un gato durante 1 minuto.",
        "Envía un mensaje de texto diciendo 'Te amo' al primer contacto en tu lista.",
        "Haz una declaración dramática de despedida como si fueras un actor de telenovela.",
        "Bebe un vaso de agua al revés.",
        "Ponte de pie y actúa como un espantapájaros durante 2 minutos.",
        "Baila como si nadie te estuviera viendo durante 1 minuto.",
        "Haz una selfie haciendo una cara ridícula y envíala a un grupo de amigos.",
        "Haz un dibujo de alguien en la habitación con los ojos cerrados.",
        "Camina por la habitación como si estuvieras en la luna durante 1 minuto.",
        "Ponte algo absurdo como sombrero y úsalo durante el resto del juego.",
        "Interpreta una escena dramática como si estuvieras en una película de acción.",
        "Haz una lista de 5 cosas embarazosas sobre ti en voz alta.",
        "Canta una canción famosa pero cambiando la letra por palabras relacionadas con comida.",
        "Escribe un mensaje absurdo y publícalo en tus redes sociales.",
        "Actúa como si fueras un presentador de televisión durante 3 minutos.",
        "Imita el baile más viral que recuerdes.",
        "Toma una foto de tu pie y envíala a alguien al azar.",
        "Habla usando solo preguntas durante los próximos 3 minutos.",
        "Camina por la habitación como si fueras un supermodelo en una pasarela.",
        "Di un cumplido extraño pero sincero a cada persona en la habitación.",
        "Finge que estás en una entrevista de trabajo muy incómoda.",
        "Haz una pose de yoga extraña y mantenla durante 20 segundos.",
        "Ponte un par de zapatos que no sean tuyos durante el resto del juego.",
        "Saca tu mejor cara de 'selfie' exagerada y muéstrala al grupo.",
        "Imita a un personaje famoso o de dibujos animados y deja que los demás adivinen quién es.",
        "Bebe algo con una cuchara en lugar de un vaso.",
        "Camina hacia atrás hasta tu próximo turno.",
        "Envía un mensaje a un amigo pidiéndole un consejo absurdo.",
        "Habla con una voz robótica hasta que alguien adivine una palabra que pienses en secreto.",
        "Ponte a aplaudir como si hubieras ganado un premio importante.",
        "Interpreta a un DJ famoso mientras alguien pone una canción.",
        "Haz 5 saltos de tijera mientras intentas decir el abecedario.",
        "Saca algo de tu bolso/mochila y actúa como si fuera tu objeto más preciado.",
        "Imita el sonido de una máquina o herramienta hasta que alguien adivine cuál es.",
        "Escribe una frase al azar y envíala a un contacto sin contexto.",
        "Haz como si estuvieras en una llamada telefónica muy incómoda.",
        "Ponte de pie y cuenta un chiste sin reírte.",
        "Camina como si fueras un robot con una batería baja.",
        "Tómate una foto en la posición más rara que puedas imaginar.",
        "Baila como si estuvieras en una película de Bollywood.",
        "Imita la voz de alguien en la habitación hasta que lo reconozcan.",
        "Habla como un anciano o anciana durante los próximos 3 minutos.",
        "Crea un apodo para cada persona en la habitación y dilo en voz alta.",
        "Haz una pose para una 'foto imaginaria' como si fueras una celebridad.",
        "Canta una canción sin usar palabras reales, solo sonidos.",
        "Haz una carrera de 'carretilla' con otra persona (uno camina con las manos mientras el otro sostiene sus pies).",
        "Camina como si fueras un pingüino durante 2 minutos.",
        "Haz una mímica de una película famosa y deja que los demás adivinen cuál es.",
        "Haz una historia inventada con la palabra más rara que alguien mencione.",
        "Finge ser un camarero/a elegante y sirve algo imaginario.",
        "Cuenta tu historia más embarazosa en 30 segundos.",
        "Crea un anuncio ridículo sobre un producto imaginario.",
        "Finge que estás corriendo una maratón mientras haces comentarios como si fueras un comentarista deportivo.",
        "Habla con un tono súper dramático sobre un tema cotidiano, como hacer café.",
        "Haz un reto físico: toca tus pies sin doblar las rodillas o haz el equilibrio en una pierna durante 30 segundos.",
        "Camina por la habitación como si estuvieras en cámara lenta.",
        "Interpreta a un chef preparando un plato imaginario y describe los ingredientes que usas.",
        "Ríe como si fueras un villano de película durante 1 minuto."
    ]
}
